### ISSUE TITLE
Put Back doesn't work on High Sierra

### ISSUE THREAD

**Issue by Cykelero** [sindresorhus/macos-trash#5] opened 2018-03-28 17:20 UTC
Testing `trash` on macOS 10.13.3, the option to Put Back deleted files doesn't show up.

I reproduced by simply creating a file in my Downloads folder using `touch`, then deleting it with `trash`. “Put Back” doesn't appear as an option when right-clicking the file in the Trash.

I hope that's not a bug in the macOS API 😖

**Comment by sindresorhus** [comment] 2018-03-28 19:30
Duplicate of #4

**Closed by sindresorhus** 2018-03-28 19:30 UTC

**Comment by Cykelero** [comment] 2018-03-28 20:13
Oh, I thought that other issue only was for fails when trashing multiple files at once, sorry!
